name: dage
description: age encryption implementation using Dart. age is a modern file encryption format with multiple pluggable recipients, and seekable streaming encryption.
version: 0.0.2
homepage: https://github.com/Producement/dage

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.1
  async: ^2.9.0
  bech32: ^0.2.1
  collection: ^1.16.0
  convert: ^3.0.1
  cryptography: ^2.0.5
  logging: ^1.0.2
  pointycastle: ^3.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0