name: dage
description: age encryption implementation using Dart. age is a modern file encryption format with multiple pluggable recipients, and seekable streaming encryption.
version: 1.0.8
homepage: https://github.com/Producement/dage

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  bech32: ^0.2.2
  collection: ^1.18.0
  convert: ^3.1.1
  cryptography: ^2.7.0
  logging: ^1.2.0
  pointycastle: ^3.7.4

dev_dependencies:
  path: ^1.9.0
  lints: ^3.0.0
  test: ^1.25.2
  crypto: ^3.0.3
