name: Artifacts
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{fromJSON(matrix.build).os}}
    strategy:
      matrix:
        build: ['{"os": "windows-latest", "exe": "dage-windows-amd64.exe"}', '{"os": "ubuntu-latest", "exe": "dage-linux-amd64"}', '{"os": "macos-latest", "exe": "dage-darwin-amd64"}']
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get
      - name: Compile
        run: dart compile exe bin/dage.dart -o ${{fromJSON(matrix.build).exe}}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{fromJSON(matrix.build).exe}}
          path: bin/${{fromJSON(matrix.build).exe}}
