name: Dart
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze

      - name: Activate coverage
        if: github.event_name == 'pull_request'
        run: dart pub global activate coverage

      - name: Test with coverage
        if: github.event_name == 'pull_request'
        run: dart pub global run coverage:test_with_coverage

      - name: Test
        if: github.event_name != 'pull_request'
        run: dart test

      - name: Collect coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        if: github.event_name == 'pull_request'
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.PAT }}
