name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for artifacts
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.sha }}
          check-name: 'Artifacts uploaded'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait for tests
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.sha }}
          check-name: 'Test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dage-*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dage-*
